### ISSUE TITLE
Feature request: Rotate 90 degrees

### ISSUE THREAD

**Issue by markanini** [anzbert/beat_pads#25]
Please consider the option to rotate the layout 90 degress. This would extend the available note range on many devices.

**Comment by anzbert** [comment]
You're not wrong about the note range in vertical direction, at least. 
Unfortunately it's not a quick fix to still make it work with all the controls. It would require a bit of a layout rewrite, I think.
If you don't care about janky layout, at least concerning the faders and other controls next to the pads, I guess you could compile the app with the rotation lock removed. That would be quite easy to do, but of course.

If you are interested in that I could guide to how to do it.

Are you on Android or iOS?

**Comment by markanini** [comment]
I'm on Android. I'll think about how much I really need the rotated layout before bothering you about the guide.

**Comment by anzbert** [comment]
ok i'll close this issue until then. thx for the feedback!
