### ISSUE TITLE
Feature Request: Note layout customization

### ISSUE THREAD

**Issue by markanini** [anzbert/beat_pads#26]
I would find it useful to have the option of minor thirds in the horizontal axis, as an option to chromatic. If you are not ready to add this into the app perhaps you can guide me?

**Comment by anzbert** [comment]
That means horizontal would be minor thirds, or 3 semitones, and what would the vertical interval be?

**Comment by markanini** [comment]
Horizontal thirds, vertical fifths.

**Comment by markanini** [comment]
Strike that I meant major thrids horizontal, although both could be useful to perform with, just that major thirds is used more.

For instance:
Harmonic table layout is Major thirds horizontally, fiths vertically.
Wicky-Hayden table layout is whole tones horizontally, fiths vertically.

**Comment by anzbert** [comment]
Ok that shouldn't be too hard to add. Just another layout in this file:

https://github.com/anzbert/beat_pads/blob/main/lib%2Fservices%2Flayout%2Fpad_layouts.dart

The harmonic table reminds me of this weird midi controller I used to have. The c-thru music axis 49.

I could probably add that layout when I get some time. But that's where it would go. If you want to do it yourself.

**Comment by markanini** [comment]
Oh, can you believe the Axis 49 goes for $1000 used these day_ I also found a clone effort stated last year that looks promising. The HT layout is less elegant on a grid, but it\s good for chord oriented performance still IMO.

**Comment by anzbert** [comment]
absolutely crazy. i think i sold it for 300 like 10 years ago. honestly, it was a bit of a novelty item and it probably still is.
all the HT info i can find online seems to require a hex grid. do you have a good source somewhere on these layouts for square grids?

**Comment by markanini** [comment]
All I got is:
1. http://terpstrakeyboard.com/play-it-now/ Maps it this way when using the pc keyboard for input. According to a forum post the webapp is endorsed by the creator of the Terpstra keyboard, a predecessor to Lumatone FWIW.
2. My testing showed that intervals, chords, scales on the square grid is directionally the same an on a hex grid, except rotated +45 degress. I used Isokeys android app as a reference.
3. Maybe at some point it will be included in the midimech project. The developer did consider it as one point and I've offered my help as a tester.

**Comment by anzbert** [comment]
I see what you mean. If you shift every second row of the harmonic table half a hexagon down, you get a square grid. I guess that's how you arrived at the fifth one way, and major third to the right and minor third to the left.

I am just wondering where the different octaves are. I'll look into it.

It should just boil down to a grid building algorithm, pretty much like what I did for the Magic Tone Network layout in the app for Andreas (same first name as me) from xpresspads.com

https://www.xpresspads.com/magic-tone-network-exercise-block-01-introduction/

I am still a bit busy at the moment though. But eventually I should get some time to add this layout.

**Comment by anzbert** [comment]
ok i've implemented the harmonic table, but quickly realised that it doesnt translate well to a square grid, unless i am missing something.

this is the original:
![image](https://github.com/anzbert/beat_pads/assets/38823700/851b1e5a-6597-4ce4-a321-6311e0b36430)

and i've went ahead and shifted every second column down by half a box, which results in this:

![image](https://github.com/anzbert/beat_pads/assets/38823700/ddd16e50-dea4-47c5-bd13-4f43697cdf1d)

as you can see on the Cs, for example, every second C has different intervals next to it, which doesnt seem intuitive unfortunately. There must be a reason why the harmonic table requires a hex grid.

Maybe give the Magic Tone Network a go instead? i think thats works better in a square grid.

I am open to suggestions though!!

**Comment by markanini** [comment]
That's different from what I had in mind:
![image](https://github.com/anzbert/beat_pads/assets/15148553/9e76edee-0724-4747-a0a3-27bba8f63bdf)

**Comment by anzbert** [comment]
ahhh thx for that. now i get it. i was overthinking 🤦‍♂️.

ive implemented it into a new branch called harmonictable. you can compile it and test it. should work fine :)

**Comment by anzbert** [comment]
actually i might release that in a minor update asap

**Comment by anzbert** [comment]
ok.. ive submitted the new version with the harmonic table for review and it should be available within 48h. usually it's quicker though.

i guess i can close this issue ?!

**Comment by markanini** [comment]
If you want to know, played with it for a little bit now. I feel it's a nice implementation, all the chordal ideas I get with this layout on a hex grid carries over to well the square grid.

**Comment by anzbert** [comment]
That's great!

Thx for providing the idea and explanation for it! I'll give it a shot in the coming days.

**Comment by anzbert** [comment]
Btw @markanini  . Do you think the wicki Hayden layout is worth investigating as well? Would you use it over the harmonic table?

**Comment by anzbert** [comment]
would you agree with this wicki layout?

![image](https://github.com/anzbert/beat_pads/assets/38823700/bdd241f9-c2ca-4181-9572-153f31da8c03)

thanks for the input again :)

**Comment by anzbert** [comment]
Ok I am reopening this issue, since I believe it would be best to have a mode in the future that allows free adjustment of vertical and horizontal intervals. 
That would cover all the discussed layouts and more.

Could be a while until I get to it, since I just went back to uni to do a postgrad cert, but eventually that could be an idea to pursue.

**Comment by anzbert** [comment]
Thx for the feedback @markanini again.

Implementing the custom grid option was actually a lot quicker than I thought. So I've just submitted a new version for review. It should be live not too long from now. 

What I've done is remove the harmonic table and tritone layout in favor of a fully custom mode, which can easily create a Harmonic Table, Wicki Hayden or Tritone grid, among any other X and Y interval combination. I only left the most commonly used standard layouts in place (major 3rd, 4th and 5th).

I hope that suits you and everyone else interested in those!

Enjoy and let me know how you go 😃

**Comment by markanini** [comment]
That totally makes a better solution. Thanks to it I found a better Harmonic table implementation with X:4 Y:3. And Midimech is also achievable which is a good allrounder layout. Great stuff.
